### ISSUE TITLE
Please add compilers.

### ISSUE THREAD

**Issue by isuruf** [conda-forge/fastavro-feedstock#39]
Example https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L35

**Comment by scottbelden** [comment]
I'll be honest, I don't use `conda` or really know all the details about the recipe file, but looking at a [previous PR test output](https://circleci.com/gh/conda-forge/fastavro-feedstock/215?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) it looks like the cython files were compiled. Or am I reading this wrong?

**Comment by scottbelden** [comment]
I think this has been resolved via https://github.com/conda-forge/fastavro-feedstock/pull/40
